// The slugs here must exactly match the `data-district` values baked into
// src/assets/karnataka-districts-map.svg — that's how map clicks and admin
// records line up. Names are the SVG's own `title` attributes.
export const KARNATAKA_DISTRICTS = [
  { slug: 'bidar', name: 'Bidar' },
  { slug: 'yadgir', name: 'Yadgir' },
  { slug: 'kalaburagi', name: 'Kalburgi' },
  { slug: 'belagavi', name: 'Belagavi' },
  { slug: 'ballari', name: 'Ballari' },
  { slug: 'chikkaballapura', name: 'Chikkaballapura' },
  { slug: 'kolar', name: 'Kolara' },
  { slug: 'chikkamangaluru', name: 'Chikkamagaluru' },
  { slug: 'hassan', name: 'Hassan' },
  { slug: 'ramanagara', name: 'Ramanagara' },
  { slug: 'bengaluru-rural', name: 'Bengaluru Rural' },
  { slug: 'bengaluru-urban', name: 'Bengaluru Urban' },
  { slug: 'mandya', name: 'Mandya' },
  { slug: 'kodagu', name: 'Kodagu' },
  { slug: 'tumakuru', name: 'Tumakuru' },
  { slug: 'raichur', name: 'Raichur' },
  { slug: 'koppal', name: 'Koppal' },
  { slug: 'bagalkote', name: 'Bagalkote' },
  { slug: 'vijayapura', name: 'Vijayapura' },
  { slug: 'haveri', name: 'Haveri' },
  { slug: 'gadag', name: 'Gadag' },
  { slug: 'mysuru', name: 'Mysuru' },
  { slug: 'chamarajanagara', name: 'Chamarajanagara' },
  { slug: 'shivamogga', name: 'Shivamogga' },
  { slug: 'davangere', name: 'Davanagere' },
  { slug: 'chitradurga', name: 'Chitradurga' },
  { slug: 'dakshina-kannada', name: 'Dakshina Kannada' },
  { slug: 'udupi', name: 'Udupi' },
  { slug: 'uttara-kannada', name: 'Uttara Kannada' },
  { slug: 'dharwad', name: 'Dharwad' },
]
