export const ROUTES = {
  HOME: '/',
  ABOUT_US: '/about-us',
  EXPORTER_CORNER: '/exporter-corner',
  GEOGRAPHICAL_INDICATIONS: '/geographical-indications',
  DOWNLOADS: '/downloads',
  EVENTS: '/events',
  CONTACT: '/contact',
  PAGE: '/:slug',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_LEADERS: '/admin/leaders',
  ADMIN_HOMEPAGE_CONTENT: '/admin/homepage-content',
  ADMIN_DISTRICTS: '/admin/districts',
  ADMIN_FOCUS_SECTORS: '/admin/focus-sectors',
  ADMIN_GI_PRODUCTS: '/admin/gi-products',
  ADMIN_OFFICES: '/admin/offices',
  ADMIN_STAFF: '/admin/staff',
  ADMIN_EVENTS: '/admin/events',
  ADMIN_DOWNLOADS: '/admin/downloads',
  ADMIN_PAGES: '/admin/pages',
  ADMIN_NEWSLETTER: '/admin/newsletter',
}
